name: Compiling-TeX
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
      - drafting

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:

    - name: Set up Git repository
      uses: actions/checkout@v1

    - name: Compile Example
      uses: xu-cheng/latex-action@master
      with:
        root_file: main.tex
        working_directory: doc

    - name: Check pdf files
      run: |
        file doc/main.pdf | grep -q ' PDF '

    - name: Upload
      run: |
        # configure git
        git config --global user.name "mxochicale"
        git config --global user.email "perez.xochicale@gmail.com"
        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git clone --depth=1 --branch pdfs git@github.com:mxochicale/the2020.git "$GITHUB_WORKSPACE/deploy"
        cp -f doc/main.pdf  "$GITHUB_WORKSPACE/deploy/entry.pdf"
        cd "$GITHUB_WORKSPACE/deploy"
        git add entry.pdf
        git commit -m "[github actions] deploy"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}